In [40]:
import numpy as np

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17])

In [4]:
type(array1)

numpy.ndarray

numpy의 ndarray

In [11]:
array1.shape

(7,)

In [13]:
array1.size

7

size shows #/factors

In [8]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [9]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
array2.shape

(2, 4)

#/rows = 2, #/columns = 4

nd means n-dimensional

# 숫자 리스트 만들기

## 일반 숫자

In [16]:
array1 = numpy.full(6, 7)

6개의 7

In [23]:
print(array1)

[1 1 1 1 1 1]


## 0으로 채우기, 1로 채우기

In [24]:
array1 = numpy.full(6, 0)

In [25]:
array2 = numpy.zeros(6, dtype = int)

In [26]:
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [27]:
array1 = numpy.full(6, 1)
print(array1)
array2 = numpy.ones(6, dtype = int)
print(array2)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


## 랜덤한 값으로 채우기

In [29]:
array1 = numpy.random.random(6)

print(array1)

[0.01896488 0.37693886 0.92527158 0.86278934 0.69552894 0.16145351]


## 연속된 값으로 채우기

In [31]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [33]:
array2 = numpy.arange(2, 7)
print(array2)

[2 3 4 5 6]


In [50]:
array3 = numpy.arange(2, 20, 2)
print(array3)

[ 2  4  6  8 10 12 14 16 18]


# array 슬라이싱과 인덱싱

## array 인덱싱

In [36]:
array3[0]

2

In [37]:
array3[-1]

18

In [38]:
array3[[2, 5, 7]]

array([ 6, 12, 16])

In [41]:
array2 = np.array([2, 5, 7])

In [51]:
array3[array2]

array([ 6, 12, 16])

## array 슬라이싱

In [43]:
array3[2:7]

array([ 6,  8, 10, 12, 14])

In [48]:
array3[:3]

array([ 6,  8, 10, 12, 14, 16, 18])

In [49]:
array3[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [46]:
array3[2:11:2]

array([ 6, 10, 14, 18])

# numpy 기본연산

In [52]:
array3 * 2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [53]:
array3 / 2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
array3 + 2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
array4 = array3 + 3

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [59]:
array3 + array4

array([25, 29, 33, 37, 41, 45, 49, 53, 57])

In [61]:
array3 / array4

array([0.78571429, 0.8125    , 0.83333333, 0.85      , 0.86363636,
       0.875     , 0.88461538, 0.89285714, 0.9       ])

## numpy 불린 연산

In [62]:
array3 < 5

array([False, False, False, False, False, False, False, False, False])

In [64]:
array3 % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True])

In [67]:
booleans = np.array([False, False, True, False, False, True, False, False, True])

In [68]:
np.where(booleans)

(array([2, 5, 8], dtype=int64),)

True값이 되는 index를 찾아준다

In [71]:
filter = np.where(array3 % 3 == 0)

In [72]:
array3[filter]

array([15, 21, 27])

3으로 나누어지는 것들만 filter함

# 통계

## 최댓값과 최솟값

In [73]:
print(array3.max())
print(array3.min())

27
11


## 평균값

In [74]:
print(array3.mean())

19.0


## 중앙값 (은 numpy의 메소드)

In [75]:
print(np.median(array3)) 

19.0


## 표준편차와 분산

In [76]:
print(array3.std())
print(array3.var())

5.163977794943222
26.666666666666668
